<?php

namespace App\Services;

use App\Models\User;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;

class QrCodeService
{
    /**
     * Generate QR Token untuk user (berlaku 1 hari)
     */
    public static function generateToken(User $user): string
    {
        $today = now('Asia/Jakarta')->toDateString();

        $token = hash_hmac(
            'sha256',
            $user->id . '|' . $user->nisn . '|' . $today,
            config('app.key')
        );

        $user->update([
            'qr_token' => $token,
            'qr_generated_at' => now('Asia/Jakarta'),
            'qr_token_used_at' => null,
        ]);
        
        Log::info('QR Token generated', [
            'user_id' => $user->id,
            'token_preview' => substr($token, 0, 10) . '...'
        ]);
        
        return $token;
    }
    
    /**
     * Generate QR Code Image (Base64)
     */
    public static function generateQrCode(User $user): string
    {
        $token = $user->qr_token ?? self::generateToken($user);

        // Format payload: ABSEN|{token}
        $payload = 'ABSEN|' . $token;

        $qrCode = QrCode::format('png')
            ->size(350)
            ->errorCorrection('M')  // Medium error correction
            ->margin(2)
            ->generate($payload);

        return 'data:image/png;base64,' . base64_encode($qrCode);
    }
    
    /**
     * Validate QR Code (return user atau error)
     */
    public static function validateQrCode(string $qrData): array
    {
        // Cek format
        if (!str_starts_with($qrData, 'ABSEN|')) {
            Log::warning('QR: Format invalid', ['data' => substr($qrData, 0, 30)]);
            return ['error' => 'FORMAT_INVALID'];
        }

        // Extract token
        $token = str_replace('ABSEN|', '', $qrData);
        
        // Cari user berdasarkan token
        $user = User::where('qr_token', $token)->first();

        if (!$user) {
            Log::warning('QR: Token tidak ditemukan di database', [
                'token_preview' => substr($token, 0, 15) . '...'
            ]);
            return ['error' => 'TOKEN_NOT_FOUND'];
        }

        // Token hanya berlaku untuk hari yang sama dengan tanggal generate
        $today = now('Asia/Jakarta')->toDateString();
        $generatedDate = $user->qr_generated_at 
            ? $user->qr_generated_at->toDateString() 
            : null;

        if (!$generatedDate || $generatedDate !== $today) {
            Log::warning('QR: Token expired atau bukan hari ini', [
                'user_id' => $user->id,
                'generated_date' => $generatedDate,
                'today' => $today
            ]);
            return ['error' => 'TOKEN_EXPIRED'];
        }

        Log::info('QR: Token valid', [
            'user_id' => $user->id,
            'name' => $user->name,
            'nisn' => $user->nisn
        ]);

        return ['user' => $user];
    }

    /**
     * Regenerate QR Token (dipanggil manual oleh user)
     */
    public static function regenerateToken(User $user): string
    {
        Log::info('QR Token regenerated by user', ['user_id' => $user->id]);
        return self::generateToken($user);
    }
    
    /**
     * Get informasi penggunaan QR terakhir
     */
    public static function getLastUsage(User $user): ?array
    {
        $lastAttendance = \App\Models\Attendance::where('user_id', $user->id)
            ->where(function($q) {
                $q->where('check_in_method', 'qr_backup')
                  ->orWhere('check_out_method', 'qr_backup');
            })
            ->latest('date')
            ->first();
        
        if (!$lastAttendance) {
            return null;
        }
        
        return [
            'date' => $lastAttendance->date,
            'type' => $lastAttendance->check_in_method === 'qr_backup' ? 'Check-In' : 'Check-Out',
            'time' => $lastAttendance->check_in_method === 'qr_backup' 
                ? $lastAttendance->check_in->format('H:i:s')
                : $lastAttendance->check_out->format('H:i:s')
        ];
    }
}